WELCOME_TEXT = "<b>AION</b>\n\nВыбери раздел меню."
NEW_CALC_TEXT = "<b>Новый расчёт</b>\n\nРаздел подключается."
NAV_TEXT = "<b>Навигация</b>\n\nРаздел подключается."
DYNAMICS_TEXT = "<b>Динамика</b>\n\nРаздел подключается."
HISTORY_TEXT = "<b>История</b>\n\nРаздел подключается."
PROFILE_TEXT = "<b>Профиль</b>\n\nРаздел подключается."
SETTINGS_TEXT = "<b>Настройки</b>\n\nРаздел подключается."
ABOUT_TEXT = "<b>О системе</b>\n\nAION — Biological Upgrade System."